-- Localise demo content created by earlier (English) seeds. Matches by slug / SKU / exact English text,
-- so it only touches untouched demo rows and is a no-op on fresh databases.

UPDATE "Color" SET "name" = 'Чорний' WHERE "slug" = 'black' AND "name" = 'Black';
UPDATE "ProductImage" SET "colorName" = 'Чорний', "alt" = replace("alt", ' — Black', ' — Чорний') WHERE "colorName" = 'Black';
UPDATE "OrderItem" SET "color" = 'Чорний' WHERE "color" = 'Black';
UPDATE "Color" SET "name" = 'Білий' WHERE "slug" = 'white' AND "name" = 'White';
UPDATE "ProductImage" SET "colorName" = 'Білий', "alt" = replace("alt", ' — White', ' — Білий') WHERE "colorName" = 'White';
UPDATE "OrderItem" SET "color" = 'Білий' WHERE "color" = 'White';
UPDATE "Color" SET "name" = 'Сірий' WHERE "slug" = 'grey' AND "name" = 'Grey';
UPDATE "ProductImage" SET "colorName" = 'Сірий', "alt" = replace("alt", ' — Grey', ' — Сірий') WHERE "colorName" = 'Grey';
UPDATE "OrderItem" SET "color" = 'Сірий' WHERE "color" = 'Grey';
UPDATE "Color" SET "name" = 'Коричневий' WHERE "slug" = 'brown' AND "name" = 'Brown';
UPDATE "ProductImage" SET "colorName" = 'Коричневий', "alt" = replace("alt", ' — Brown', ' — Коричневий') WHERE "colorName" = 'Brown';
UPDATE "OrderItem" SET "color" = 'Коричневий' WHERE "color" = 'Brown';
UPDATE "Color" SET "name" = 'Бежевий' WHERE "slug" = 'beige' AND "name" = 'Beige';
UPDATE "ProductImage" SET "colorName" = 'Бежевий', "alt" = replace("alt", ' — Beige', ' — Бежевий') WHERE "colorName" = 'Beige';
UPDATE "OrderItem" SET "color" = 'Бежевий' WHERE "color" = 'Beige';
UPDATE "Color" SET "name" = 'Блакитний' WHERE "slug" = 'blue' AND "name" = 'Blue';
UPDATE "ProductImage" SET "colorName" = 'Блакитний', "alt" = replace("alt", ' — Blue', ' — Блакитний') WHERE "colorName" = 'Blue';
UPDATE "OrderItem" SET "color" = 'Блакитний' WHERE "color" = 'Blue';
UPDATE "Color" SET "name" = 'Оливковий' WHERE "slug" = 'green' AND "name" = 'Green';
UPDATE "ProductImage" SET "colorName" = 'Оливковий', "alt" = replace("alt", ' — Green', ' — Оливковий') WHERE "colorName" = 'Green';
UPDATE "OrderItem" SET "color" = 'Оливковий' WHERE "color" = 'Green';
UPDATE "Category" SET "name" = 'Спорт', "seoTitle" = 'Спорт — VELLA', "description" = CASE WHEN "description" = 'Active від VELLA.' THEN 'Спорт від VELLA.' ELSE "description" END WHERE "slug" = 'active' AND "name" = 'Active';
UPDATE "Category" SET "name" = 'Одяг', "seoTitle" = 'Одяг — VELLA', "description" = CASE WHEN "description" = 'Clothing від VELLA.' THEN 'Одяг від VELLA.' ELSE "description" END WHERE "slug" = 'clothing' AND "name" = 'Clothing';
UPDATE "Category" SET "name" = 'Аксесуари', "seoTitle" = 'Аксесуари — VELLA', "description" = CASE WHEN "description" = 'Accessories від VELLA.' THEN 'Аксесуари від VELLA.' ELSE "description" END WHERE "slug" = 'accessories' AND "name" = 'Accessories';
UPDATE "Category" SET "name" = 'Комплекти', "seoTitle" = 'Комплекти — VELLA', "description" = CASE WHEN "description" = 'Sets від VELLA.' THEN 'Комплекти від VELLA.' ELSE "description" END WHERE "slug" = 'sets' AND "name" = 'Sets';
UPDATE "Category" SET "name" = 'Спортивні топи', "seoTitle" = 'Спортивні топи — VELLA', "description" = CASE WHEN "description" = 'Sports Bras від VELLA.' THEN 'Спортивні топи від VELLA.' ELSE "description" END WHERE "slug" = 'sports-bras' AND "name" = 'Sports Bras';
UPDATE "Category" SET "name" = 'Спортивні легінси', "seoTitle" = 'Спортивні легінси — VELLA', "description" = CASE WHEN "description" = 'Active Leggings від VELLA.' THEN 'Спортивні легінси від VELLA.' ELSE "description" END WHERE "slug" = 'active-leggings' AND "name" = 'Active Leggings';
UPDATE "Category" SET "name" = 'Велосипедки', "seoTitle" = 'Велосипедки — VELLA', "description" = CASE WHEN "description" = 'Bike Shorts від VELLA.' THEN 'Велосипедки від VELLA.' ELSE "description" END WHERE "slug" = 'bike-shorts' AND "name" = 'Bike Shorts';
UPDATE "Category" SET "name" = 'Худі', "seoTitle" = 'Худі — VELLA', "description" = CASE WHEN "description" = 'Hoodies від VELLA.' THEN 'Худі від VELLA.' ELSE "description" END WHERE "slug" = 'hoodies' AND "name" = 'Hoodies';
UPDATE "Category" SET "name" = 'Світшоти', "seoTitle" = 'Світшоти — VELLA', "description" = CASE WHEN "description" = 'Sweatshirts від VELLA.' THEN 'Світшоти від VELLA.' ELSE "description" END WHERE "slug" = 'sweatshirts' AND "name" = 'Sweatshirts';
UPDATE "Category" SET "name" = 'Футболки', "seoTitle" = 'Футболки — VELLA', "description" = CASE WHEN "description" = 'T-shirts від VELLA.' THEN 'Футболки від VELLA.' ELSE "description" END WHERE "slug" = 't-shirts' AND "name" = 'T-shirts';
UPDATE "Category" SET "name" = 'Топи', "seoTitle" = 'Топи — VELLA', "description" = CASE WHEN "description" = 'Tops від VELLA.' THEN 'Топи від VELLA.' ELSE "description" END WHERE "slug" = 'tops' AND "name" = 'Tops';
UPDATE "Category" SET "name" = 'Легінси', "seoTitle" = 'Легінси — VELLA', "description" = CASE WHEN "description" = 'Leggings від VELLA.' THEN 'Легінси від VELLA.' ELSE "description" END WHERE "slug" = 'leggings' AND "name" = 'Leggings';
UPDATE "Category" SET "name" = 'Штани', "seoTitle" = 'Штани — VELLA', "description" = CASE WHEN "description" = 'Pants від VELLA.' THEN 'Штани від VELLA.' ELSE "description" END WHERE "slug" = 'pants' AND "name" = 'Pants';
UPDATE "Category" SET "name" = 'Шорти', "seoTitle" = 'Шорти — VELLA', "description" = CASE WHEN "description" = 'Shorts від VELLA.' THEN 'Шорти від VELLA.' ELSE "description" END WHERE "slug" = 'shorts' AND "name" = 'Shorts';
UPDATE "Category" SET "name" = 'Куртки', "seoTitle" = 'Куртки — VELLA', "description" = CASE WHEN "description" = 'Jackets від VELLA.' THEN 'Куртки від VELLA.' ELSE "description" END WHERE "slug" = 'jackets' AND "name" = 'Jackets';
UPDATE "Category" SET "name" = 'Сумки', "seoTitle" = 'Сумки — VELLA', "description" = CASE WHEN "description" = 'Bags від VELLA.' THEN 'Сумки від VELLA.' ELSE "description" END WHERE "slug" = 'bags' AND "name" = 'Bags';
UPDATE "Category" SET "name" = 'Кепки', "seoTitle" = 'Кепки — VELLA', "description" = CASE WHEN "description" = 'Caps від VELLA.' THEN 'Кепки від VELLA.' ELSE "description" END WHERE "slug" = 'caps' AND "name" = 'Caps';
UPDATE "Category" SET "name" = 'Шкарпетки', "seoTitle" = 'Шкарпетки — VELLA', "description" = CASE WHEN "description" = 'Socks від VELLA.' THEN 'Шкарпетки від VELLA.' ELSE "description" END WHERE "slug" = 'socks' AND "name" = 'Socks';
UPDATE "Category" SET "name" = 'Інше', "seoTitle" = 'Інше — VELLA', "description" = CASE WHEN "description" = 'Other від VELLA.' THEN 'Інше від VELLA.' ELSE "description" END WHERE "slug" = 'other-accessories' AND "name" = 'Other';
UPDATE "Collection" SET "name" = 'Новий сезон', "seoTitle" = 'Новий сезон — VELLA' WHERE "slug" = 'new-season' AND "name" = 'New Season';
UPDATE "Collection" SET "name" = 'Спорт-студія', "seoTitle" = 'Спорт-студія — VELLA' WHERE "slug" = 'active-studio' AND "name" = 'Active Studio';
UPDATE "Collection" SET "name" = 'Базовий гардероб', "seoTitle" = 'Базовий гардероб — VELLA' WHERE "slug" = 'essentials' AND "name" = 'Essentials';
UPDATE "Collection" SET "name" = 'Преміум', "seoTitle" = 'Преміум — VELLA' WHERE "slug" = 'premium' AND "name" = 'Premium';
UPDATE "Collection" SET "name" = 'Літо', "seoTitle" = 'Літо — VELLA' WHERE "slug" = 'summer' AND "name" = 'Summer';
UPDATE "Product" SET "name" = 'Худі оверсайз з начосом', "seoTitle" = 'Худі оверсайз з начосом — VELLA' WHERE "sku" = 'VL-HD-001' AND "name" = 'Oversized Fleece Hoodie';
UPDATE "ProductImage" SET "alt" = replace("alt", 'Oversized Fleece Hoodie', 'Худі оверсайз з начосом') WHERE "productId" IN (SELECT "id" FROM "Product" WHERE "sku" = 'VL-HD-001');
UPDATE "OrderItem" SET "name" = 'Худі оверсайз з начосом' WHERE "sku" LIKE 'VL-HD-001-%' AND "name" = 'Oversized Fleece Hoodie';
UPDATE "Product" SET "name" = 'Худі на блискавці', "seoTitle" = 'Худі на блискавці — VELLA' WHERE "sku" = 'VL-HD-002' AND "name" = 'Zip-Through Hoodie';
UPDATE "ProductImage" SET "alt" = replace("alt", 'Zip-Through Hoodie', 'Худі на блискавці') WHERE "productId" IN (SELECT "id" FROM "Product" WHERE "sku" = 'VL-HD-002');
UPDATE "OrderItem" SET "name" = 'Худі на блискавці' WHERE "sku" LIKE 'VL-HD-002-%' AND "name" = 'Zip-Through Hoodie';
UPDATE "Product" SET "name" = 'Укорочене худі Studio', "seoTitle" = 'Укорочене худі Studio — VELLA' WHERE "sku" = 'VL-HD-003' AND "name" = 'Cropped Studio Hoodie';
UPDATE "ProductImage" SET "alt" = replace("alt", 'Cropped Studio Hoodie', 'Укорочене худі Studio') WHERE "productId" IN (SELECT "id" FROM "Product" WHERE "sku" = 'VL-HD-003');
UPDATE "OrderItem" SET "name" = 'Укорочене худі Studio' WHERE "sku" LIKE 'VL-HD-003-%' AND "name" = 'Cropped Studio Hoodie';
UPDATE "Product" SET "name" = 'Щільне худі', "seoTitle" = 'Щільне худі — VELLA' WHERE "sku" = 'VL-HD-004' AND "name" = 'Heavyweight Hoodie';
UPDATE "ProductImage" SET "alt" = replace("alt", 'Heavyweight Hoodie', 'Щільне худі') WHERE "productId" IN (SELECT "id" FROM "Product" WHERE "sku" = 'VL-HD-004');
UPDATE "OrderItem" SET "name" = 'Щільне худі' WHERE "sku" LIKE 'VL-HD-004-%' AND "name" = 'Heavyweight Hoodie';
UPDATE "Product" SET "name" = 'Класичний світшот', "seoTitle" = 'Класичний світшот — VELLA' WHERE "sku" = 'VL-SW-001' AND "name" = 'Classic Crew Sweatshirt';
UPDATE "ProductImage" SET "alt" = replace("alt", 'Classic Crew Sweatshirt', 'Класичний світшот') WHERE "productId" IN (SELECT "id" FROM "Product" WHERE "sku" = 'VL-SW-001');
UPDATE "OrderItem" SET "name" = 'Класичний світшот' WHERE "sku" LIKE 'VL-SW-001-%' AND "name" = 'Classic Crew Sweatshirt';
UPDATE "Product" SET "name" = 'Світшот з коротким замком', "seoTitle" = 'Світшот з коротким замком — VELLA' WHERE "sku" = 'VL-SW-002' AND "name" = 'Boxy Half-Zip Sweatshirt';
UPDATE "ProductImage" SET "alt" = replace("alt", 'Boxy Half-Zip Sweatshirt', 'Світшот з коротким замком') WHERE "productId" IN (SELECT "id" FROM "Product" WHERE "sku" = 'VL-SW-002');
UPDATE "OrderItem" SET "name" = 'Світшот з коротким замком' WHERE "sku" LIKE 'VL-SW-002-%' AND "name" = 'Boxy Half-Zip Sweatshirt';
UPDATE "Product" SET "name" = 'Світшот з брашованої бавовни', "seoTitle" = 'Світшот з брашованої бавовни — VELLA' WHERE "sku" = 'VL-SW-003' AND "name" = 'Brushed Cotton Sweatshirt';
UPDATE "ProductImage" SET "alt" = replace("alt", 'Brushed Cotton Sweatshirt', 'Світшот з брашованої бавовни') WHERE "productId" IN (SELECT "id" FROM "Product" WHERE "sku" = 'VL-SW-003');
UPDATE "OrderItem" SET "name" = 'Світшот з брашованої бавовни' WHERE "sku" LIKE 'VL-SW-003-%' AND "name" = 'Brushed Cotton Sweatshirt';
UPDATE "Product" SET "name" = 'Базова футболка', "seoTitle" = 'Базова футболка — VELLA' WHERE "sku" = 'VL-TS-001' AND "name" = 'Essential Crew Tee';
UPDATE "ProductImage" SET "alt" = replace("alt", 'Essential Crew Tee', 'Базова футболка') WHERE "productId" IN (SELECT "id" FROM "Product" WHERE "sku" = 'VL-TS-001');
UPDATE "OrderItem" SET "name" = 'Базова футболка' WHERE "sku" LIKE 'VL-TS-001-%' AND "name" = 'Essential Crew Tee';
UPDATE "Product" SET "name" = 'Щільна футболка оверсайз', "seoTitle" = 'Щільна футболка оверсайз — VELLA' WHERE "sku" = 'VL-TS-002' AND "name" = 'Oversized Heavy Tee';
UPDATE "ProductImage" SET "alt" = replace("alt", 'Oversized Heavy Tee', 'Щільна футболка оверсайз') WHERE "productId" IN (SELECT "id" FROM "Product" WHERE "sku" = 'VL-TS-002');
UPDATE "OrderItem" SET "name" = 'Щільна футболка оверсайз' WHERE "sku" LIKE 'VL-TS-002-%' AND "name" = 'Oversized Heavy Tee';
UPDATE "Product" SET "name" = 'Приталена футболка в рубчик', "seoTitle" = 'Приталена футболка в рубчик — VELLA' WHERE "sku" = 'VL-TS-003' AND "name" = 'Fitted Rib Tee';
UPDATE "ProductImage" SET "alt" = replace("alt", 'Fitted Rib Tee', 'Приталена футболка в рубчик') WHERE "productId" IN (SELECT "id" FROM "Product" WHERE "sku" = 'VL-TS-003');
UPDATE "OrderItem" SET "name" = 'Приталена футболка в рубчик' WHERE "sku" LIKE 'VL-TS-003-%' AND "name" = 'Fitted Rib Tee';
UPDATE "Product" SET "name" = 'Лонгслів Studio', "seoTitle" = 'Лонгслів Studio — VELLA' WHERE "sku" = 'VL-TS-004' AND "name" = 'Long Sleeve Studio Tee';
UPDATE "ProductImage" SET "alt" = replace("alt", 'Long Sleeve Studio Tee', 'Лонгслів Studio') WHERE "productId" IN (SELECT "id" FROM "Product" WHERE "sku" = 'VL-TS-004');
UPDATE "OrderItem" SET "name" = 'Лонгслів Studio' WHERE "sku" LIKE 'VL-TS-004-%' AND "name" = 'Long Sleeve Studio Tee';
UPDATE "Product" SET "name" = 'Безшовна майка', "seoTitle" = 'Безшовна майка — VELLA' WHERE "sku" = 'VL-TP-001' AND "name" = 'Seamless Tank Top';
UPDATE "ProductImage" SET "alt" = replace("alt", 'Seamless Tank Top', 'Безшовна майка') WHERE "productId" IN (SELECT "id" FROM "Product" WHERE "sku" = 'VL-TP-001');
UPDATE "OrderItem" SET "name" = 'Безшовна майка' WHERE "sku" LIKE 'VL-TP-001-%' AND "name" = 'Seamless Tank Top';
UPDATE "Product" SET "name" = 'Укорочений топ у рубчик', "seoTitle" = 'Укорочений топ у рубчик — VELLA' WHERE "sku" = 'VL-TP-002' AND "name" = 'Ribbed Crop Top';
UPDATE "ProductImage" SET "alt" = replace("alt", 'Ribbed Crop Top', 'Укорочений топ у рубчик') WHERE "productId" IN (SELECT "id" FROM "Product" WHERE "sku" = 'VL-TP-002');
UPDATE "OrderItem" SET "name" = 'Укорочений топ у рубчик' WHERE "sku" LIKE 'VL-TP-002-%' AND "name" = 'Ribbed Crop Top';
UPDATE "Product" SET "name" = 'Топ із запахом', "seoTitle" = 'Топ із запахом — VELLA' WHERE "sku" = 'VL-TP-003' AND "name" = 'Wrap Long Sleeve Top';
UPDATE "ProductImage" SET "alt" = replace("alt", 'Wrap Long Sleeve Top', 'Топ із запахом') WHERE "productId" IN (SELECT "id" FROM "Product" WHERE "sku" = 'VL-TP-003');
UPDATE "OrderItem" SET "name" = 'Топ із запахом' WHERE "sku" LIKE 'VL-TP-003-%' AND "name" = 'Wrap Long Sleeve Top';
UPDATE "Product" SET "name" = 'Спортивний топ Sculpt', "seoTitle" = 'Спортивний топ Sculpt — VELLA' WHERE "sku" = 'VL-BR-001' AND "name" = 'Sculpt Sports Bra';
UPDATE "ProductImage" SET "alt" = replace("alt", 'Sculpt Sports Bra', 'Спортивний топ Sculpt') WHERE "productId" IN (SELECT "id" FROM "Product" WHERE "sku" = 'VL-BR-001');
UPDATE "OrderItem" SET "name" = 'Спортивний топ Sculpt' WHERE "sku" LIKE 'VL-BR-001-%' AND "name" = 'Sculpt Sports Bra';
UPDATE "Product" SET "name" = 'Спортивний топ з перехресною спинкою', "seoTitle" = 'Спортивний топ з перехресною спинкою — VELLA' WHERE "sku" = 'VL-BR-002' AND "name" = 'Cross-Back Bra';
UPDATE "ProductImage" SET "alt" = replace("alt", 'Cross-Back Bra', 'Спортивний топ з перехресною спинкою') WHERE "productId" IN (SELECT "id" FROM "Product" WHERE "sku" = 'VL-BR-002');
UPDATE "OrderItem" SET "name" = 'Спортивний топ з перехресною спинкою' WHERE "sku" LIKE 'VL-BR-002-%' AND "name" = 'Cross-Back Bra';
UPDATE "Product" SET "name" = 'Спортивний топ високої підтримки', "seoTitle" = 'Спортивний топ високої підтримки — VELLA' WHERE "sku" = 'VL-BR-003' AND "name" = 'High Support Bra';
UPDATE "ProductImage" SET "alt" = replace("alt", 'High Support Bra', 'Спортивний топ високої підтримки') WHERE "productId" IN (SELECT "id" FROM "Product" WHERE "sku" = 'VL-BR-003');
UPDATE "OrderItem" SET "name" = 'Спортивний топ високої підтримки' WHERE "sku" LIKE 'VL-BR-003-%' AND "name" = 'High Support Bra';
UPDATE "Product" SET "name" = 'Легінси Sculpt з високою посадкою', "seoTitle" = 'Легінси Sculpt з високою посадкою — VELLA' WHERE "sku" = 'VL-LG-001' AND "name" = 'Sculpt High-Rise Leggings';
UPDATE "ProductImage" SET "alt" = replace("alt", 'Sculpt High-Rise Leggings', 'Легінси Sculpt з високою посадкою') WHERE "productId" IN (SELECT "id" FROM "Product" WHERE "sku" = 'VL-LG-001');
UPDATE "OrderItem" SET "name" = 'Легінси Sculpt з високою посадкою' WHERE "sku" LIKE 'VL-LG-001-%' AND "name" = 'Sculpt High-Rise Leggings';
UPDATE "Product" SET "name" = 'Легінси кльош', "seoTitle" = 'Легінси кльош — VELLA' WHERE "sku" = 'VL-LG-002' AND "name" = 'Flared Leggings';
UPDATE "ProductImage" SET "alt" = replace("alt", 'Flared Leggings', 'Легінси кльош') WHERE "productId" IN (SELECT "id" FROM "Product" WHERE "sku" = 'VL-LG-002');
UPDATE "OrderItem" SET "name" = 'Легінси кльош' WHERE "sku" LIKE 'VL-LG-002-%' AND "name" = 'Flared Leggings';
UPDATE "Product" SET "name" = 'Безшовні легінси в рубчик', "seoTitle" = 'Безшовні легінси в рубчик — VELLA' WHERE "sku" = 'VL-LG-003' AND "name" = 'Seamless Rib Leggings';
UPDATE "ProductImage" SET "alt" = replace("alt", 'Seamless Rib Leggings', 'Безшовні легінси в рубчик') WHERE "productId" IN (SELECT "id" FROM "Product" WHERE "sku" = 'VL-LG-003');
UPDATE "OrderItem" SET "name" = 'Безшовні легінси в рубчик' WHERE "sku" LIKE 'VL-LG-003-%' AND "name" = 'Seamless Rib Leggings';
UPDATE "Product" SET "name" = 'Легінси 7/8 з кишенями', "seoTitle" = 'Легінси 7/8 з кишенями — VELLA' WHERE "sku" = 'VL-LG-004' AND "name" = 'Pocket Leggings 7/8';
UPDATE "ProductImage" SET "alt" = replace("alt", 'Pocket Leggings 7/8', 'Легінси 7/8 з кишенями') WHERE "productId" IN (SELECT "id" FROM "Product" WHERE "sku" = 'VL-LG-004');
UPDATE "OrderItem" SET "name" = 'Легінси 7/8 з кишенями' WHERE "sku" LIKE 'VL-LG-004-%' AND "name" = 'Pocket Leggings 7/8';
UPDATE "Product" SET "name" = 'Широкі спортивні штани', "seoTitle" = 'Широкі спортивні штани — VELLA' WHERE "sku" = 'VL-PT-001' AND "name" = 'Wide-Leg Sweatpants';
UPDATE "ProductImage" SET "alt" = replace("alt", 'Wide-Leg Sweatpants', 'Широкі спортивні штани') WHERE "productId" IN (SELECT "id" FROM "Product" WHERE "sku" = 'VL-PT-001');
UPDATE "OrderItem" SET "name" = 'Широкі спортивні штани' WHERE "sku" LIKE 'VL-PT-001-%' AND "name" = 'Wide-Leg Sweatpants';
UPDATE "Product" SET "name" = 'Джогери зі стрілкою', "seoTitle" = 'Джогери зі стрілкою — VELLA' WHERE "sku" = 'VL-PT-002' AND "name" = 'Tailored Jogger';
UPDATE "ProductImage" SET "alt" = replace("alt", 'Tailored Jogger', 'Джогери зі стрілкою') WHERE "productId" IN (SELECT "id" FROM "Product" WHERE "sku" = 'VL-PT-002');
UPDATE "OrderItem" SET "name" = 'Джогери зі стрілкою' WHERE "sku" LIKE 'VL-PT-002-%' AND "name" = 'Tailored Jogger';
UPDATE "Product" SET "name" = 'Прямі трекові штани', "seoTitle" = 'Прямі трекові штани — VELLA' WHERE "sku" = 'VL-PT-003' AND "name" = 'Straight Track Pants';
UPDATE "ProductImage" SET "alt" = replace("alt", 'Straight Track Pants', 'Прямі трекові штани') WHERE "productId" IN (SELECT "id" FROM "Product" WHERE "sku" = 'VL-PT-003');
UPDATE "OrderItem" SET "name" = 'Прямі трекові штани' WHERE "sku" LIKE 'VL-PT-003-%' AND "name" = 'Straight Track Pants';
UPDATE "Product" SET "name" = 'Велосипедки', "seoTitle" = 'Велосипедки — VELLA' WHERE "sku" = 'VL-SH-001' AND "name" = 'Biker Shorts';
UPDATE "ProductImage" SET "alt" = replace("alt", 'Biker Shorts', 'Велосипедки') WHERE "productId" IN (SELECT "id" FROM "Product" WHERE "sku" = 'VL-SH-001');
UPDATE "OrderItem" SET "name" = 'Велосипедки' WHERE "sku" LIKE 'VL-SH-001-%' AND "name" = 'Biker Shorts';
UPDATE "Product" SET "name" = 'Шорти з футеру', "seoTitle" = 'Шорти з футеру — VELLA' WHERE "sku" = 'VL-SH-002' AND "name" = 'Sweat Shorts';
UPDATE "ProductImage" SET "alt" = replace("alt", 'Sweat Shorts', 'Шорти з футеру') WHERE "productId" IN (SELECT "id" FROM "Product" WHERE "sku" = 'VL-SH-002');
UPDATE "OrderItem" SET "name" = 'Шорти з футеру' WHERE "sku" LIKE 'VL-SH-002-%' AND "name" = 'Sweat Shorts';
UPDATE "Product" SET "name" = 'Шорти для бігу', "seoTitle" = 'Шорти для бігу — VELLA' WHERE "sku" = 'VL-SH-003' AND "name" = 'Running Shorts';
UPDATE "ProductImage" SET "alt" = replace("alt", 'Running Shorts', 'Шорти для бігу') WHERE "productId" IN (SELECT "id" FROM "Product" WHERE "sku" = 'VL-SH-003');
UPDATE "OrderItem" SET "name" = 'Шорти для бігу' WHERE "sku" LIKE 'VL-SH-003-%' AND "name" = 'Running Shorts';
UPDATE "Product" SET "name" = 'Легка трекова куртка', "seoTitle" = 'Легка трекова куртка — VELLA' WHERE "sku" = 'VL-JK-001' AND "name" = 'Lightweight Track Jacket';
UPDATE "ProductImage" SET "alt" = replace("alt", 'Lightweight Track Jacket', 'Легка трекова куртка') WHERE "productId" IN (SELECT "id" FROM "Product" WHERE "sku" = 'VL-JK-001');
UPDATE "OrderItem" SET "name" = 'Легка трекова куртка' WHERE "sku" LIKE 'VL-JK-001-%' AND "name" = 'Lightweight Track Jacket';
UPDATE "Product" SET "name" = 'Сорочка-куртка', "seoTitle" = 'Сорочка-куртка — VELLA' WHERE "sku" = 'VL-JK-002' AND "name" = 'Structured Overshirt Jacket';
UPDATE "ProductImage" SET "alt" = replace("alt", 'Structured Overshirt Jacket', 'Сорочка-куртка') WHERE "productId" IN (SELECT "id" FROM "Product" WHERE "sku" = 'VL-JK-002');
UPDATE "OrderItem" SET "name" = 'Сорочка-куртка' WHERE "sku" LIKE 'VL-JK-002-%' AND "name" = 'Structured Overshirt Jacket';
UPDATE "Product" SET "name" = 'Флісова куртка на блискавці', "seoTitle" = 'Флісова куртка на блискавці — VELLA' WHERE "sku" = 'VL-JK-003' AND "name" = 'Fleece Zip Jacket';
UPDATE "ProductImage" SET "alt" = replace("alt", 'Fleece Zip Jacket', 'Флісова куртка на блискавці') WHERE "productId" IN (SELECT "id" FROM "Product" WHERE "sku" = 'VL-JK-003');
UPDATE "OrderItem" SET "name" = 'Флісова куртка на блискавці' WHERE "sku" LIKE 'VL-JK-003-%' AND "name" = 'Fleece Zip Jacket';
UPDATE "Product" SET "name" = 'Шопер з канвасу', "seoTitle" = 'Шопер з канвасу — VELLA' WHERE "sku" = 'VL-BG-001' AND "name" = 'Canvas Tote Bag';
UPDATE "ProductImage" SET "alt" = replace("alt", 'Canvas Tote Bag', 'Шопер з канвасу') WHERE "productId" IN (SELECT "id" FROM "Product" WHERE "sku" = 'VL-BG-001');
UPDATE "OrderItem" SET "name" = 'Шопер з канвасу' WHERE "sku" LIKE 'VL-BG-001-%' AND "name" = 'Canvas Tote Bag';
UPDATE "Product" SET "name" = 'Спортивна сумка', "seoTitle" = 'Спортивна сумка — VELLA' WHERE "sku" = 'VL-BG-002' AND "name" = 'Gym Duffel Bag';
UPDATE "ProductImage" SET "alt" = replace("alt", 'Gym Duffel Bag', 'Спортивна сумка') WHERE "productId" IN (SELECT "id" FROM "Product" WHERE "sku" = 'VL-BG-002');
UPDATE "OrderItem" SET "name" = 'Спортивна сумка' WHERE "sku" LIKE 'VL-BG-002-%' AND "name" = 'Gym Duffel Bag';
UPDATE "Product" SET "name" = 'Кепка з вареної бавовни', "seoTitle" = 'Кепка з вареної бавовни — VELLA' WHERE "sku" = 'VL-CP-001' AND "name" = 'Washed Cotton Cap';
UPDATE "ProductImage" SET "alt" = replace("alt", 'Washed Cotton Cap', 'Кепка з вареної бавовни') WHERE "productId" IN (SELECT "id" FROM "Product" WHERE "sku" = 'VL-CP-001');
UPDATE "OrderItem" SET "name" = 'Кепка з вареної бавовни' WHERE "sku" LIKE 'VL-CP-001-%' AND "name" = 'Washed Cotton Cap';
UPDATE "Product" SET "name" = 'Спортивна кепка з нейлону', "seoTitle" = 'Спортивна кепка з нейлону — VELLA' WHERE "sku" = 'VL-CP-002' AND "name" = 'Nylon Sport Cap';
UPDATE "ProductImage" SET "alt" = replace("alt", 'Nylon Sport Cap', 'Спортивна кепка з нейлону') WHERE "productId" IN (SELECT "id" FROM "Product" WHERE "sku" = 'VL-CP-002');
UPDATE "OrderItem" SET "name" = 'Спортивна кепка з нейлону' WHERE "sku" LIKE 'VL-CP-002-%' AND "name" = 'Nylon Sport Cap';
UPDATE "Product" SET "name" = 'Високі шкарпетки, 3 пари', "seoTitle" = 'Високі шкарпетки, 3 пари — VELLA' WHERE "sku" = 'VL-SK-001' AND "name" = 'Crew Socks 3-Pack';
UPDATE "ProductImage" SET "alt" = replace("alt", 'Crew Socks 3-Pack', 'Високі шкарпетки, 3 пари') WHERE "productId" IN (SELECT "id" FROM "Product" WHERE "sku" = 'VL-SK-001');
UPDATE "OrderItem" SET "name" = 'Високі шкарпетки, 3 пари' WHERE "sku" LIKE 'VL-SK-001-%' AND "name" = 'Crew Socks 3-Pack';
UPDATE "Product" SET "name" = 'Короткі спортивні шкарпетки', "seoTitle" = 'Короткі спортивні шкарпетки — VELLA' WHERE "sku" = 'VL-SK-002' AND "name" = 'Sport Ankle Socks';
UPDATE "ProductImage" SET "alt" = replace("alt", 'Sport Ankle Socks', 'Короткі спортивні шкарпетки') WHERE "productId" IN (SELECT "id" FROM "Product" WHERE "sku" = 'VL-SK-002');
UPDATE "OrderItem" SET "name" = 'Короткі спортивні шкарпетки' WHERE "sku" LIKE 'VL-SK-002-%' AND "name" = 'Sport Ankle Socks';
UPDATE "Product" SET "name" = 'Термопляшка зі сталі', "seoTitle" = 'Термопляшка зі сталі — VELLA' WHERE "sku" = 'VL-AC-001' AND "name" = 'Steel Water Bottle';
UPDATE "ProductImage" SET "alt" = replace("alt", 'Steel Water Bottle', 'Термопляшка зі сталі') WHERE "productId" IN (SELECT "id" FROM "Product" WHERE "sku" = 'VL-AC-001');
UPDATE "OrderItem" SET "name" = 'Термопляшка зі сталі' WHERE "sku" LIKE 'VL-AC-001-%' AND "name" = 'Steel Water Bottle';
UPDATE "Product" SET "name" = 'Комплект Sculpt Studio', "seoTitle" = 'Комплект Sculpt Studio — VELLA' WHERE "sku" = 'VL-ST-001' AND "name" = 'Sculpt Studio Set';
UPDATE "ProductImage" SET "alt" = replace("alt", 'Sculpt Studio Set', 'Комплект Sculpt Studio') WHERE "productId" IN (SELECT "id" FROM "Product" WHERE "sku" = 'VL-ST-001');
UPDATE "OrderItem" SET "name" = 'Комплект Sculpt Studio' WHERE "sku" LIKE 'VL-ST-001-%' AND "name" = 'Sculpt Studio Set';
UPDATE "Product" SET "name" = 'Домашній комплект', "seoTitle" = 'Домашній комплект — VELLA' WHERE "sku" = 'VL-ST-002' AND "name" = 'Lounge Set';
UPDATE "ProductImage" SET "alt" = replace("alt", 'Lounge Set', 'Домашній комплект') WHERE "productId" IN (SELECT "id" FROM "Product" WHERE "sku" = 'VL-ST-002');
UPDATE "OrderItem" SET "name" = 'Домашній комплект' WHERE "sku" LIKE 'VL-ST-002-%' AND "name" = 'Lounge Set';
UPDATE "Product" SET "name" = 'Безшовний спортивний комплект', "seoTitle" = 'Безшовний спортивний комплект — VELLA' WHERE "sku" = 'VL-ST-003' AND "name" = 'Seamless Active Set';
UPDATE "ProductImage" SET "alt" = replace("alt", 'Seamless Active Set', 'Безшовний спортивний комплект') WHERE "productId" IN (SELECT "id" FROM "Product" WHERE "sku" = 'VL-ST-003');
UPDATE "OrderItem" SET "name" = 'Безшовний спортивний комплект' WHERE "sku" LIKE 'VL-ST-003-%' AND "name" = 'Seamless Active Set';
UPDATE "HomepageSection" SET "title" = 'Новинки та тренди' WHERE "title" = 'New & Trending';
UPDATE "HomepageSection" SET "title" = 'Категорії' WHERE "title" = 'Shop by category';
UPDATE "HomepageSection" SET "title" = 'Бестселери' WHERE "title" = 'Best Sellers';
UPDATE "HomepageSection" SET "title" = 'Нові надходження' WHERE "title" = 'New Arrivals';
UPDATE "HomepageSection" SET "title" = 'Колекції' WHERE "title" = 'Shop by collection';
UPDATE "HomepageSection" SET "title" = 'Знижки до −30%' WHERE "title" = 'Sale до −30%';
UPDATE "HomepageSection" SET "title" = 'Розпродаж' WHERE "title" = 'Sale';
UPDATE "HomepageSection" SET "label" = 'Спорт-студія', "body" = replace("body", 'Колекція Active Studio', 'Колекція «Спорт-студія»') WHERE "label" = 'Active Studio';
UPDATE "HomepageSection" SET "buttonLabel" = 'До каталогу' WHERE "buttonLabel" = 'Shop women';
UPDATE "HomepageSection" SET "button2Label" = 'Новинки' WHERE "button2Label" = 'Shop new in';
UPDATE "Banner" SET "title" = 'Спорт-студія' WHERE "title" = 'Active Studio';
UPDATE "Banner" SET "title" = 'Базовий гардероб' WHERE "title" = 'Essentials';
UPDATE "Banner" SET "title" = 'Знижки до −30%' WHERE "title" = 'Sale до −30%';
UPDATE "Settings" SET "tagline" = 'Одяг для руху та щоденного життя' WHERE "tagline" = 'Activewear & essentials';
